### ISSUE TITLE
Sanity (3.2.5) peerDependency when installed, causes deskTool to crash

### ISSUE THREAD

**Issue by karlomedallo** [sanity-io/next-sanity#315]
If I don't install the missing peerDependency (sanity), embedded studio on nextjs 13 works fine

**Comment by karlomedallo** [comment]
```
Uncaught Error: Workspace: missing context value
    at useWorkspace (index.js:706:18215)
    at DeskToolBoundary (leaf.js:4925:59)
    at renderWithHooks (react-dom.development.js:16305:18)
    at updateFunctionComponent (react-dom.development.js:19583:20)
    at mountLazyComponent (react-dom.development.js:19954:17)
    at beginWork (react-dom.development.js:21588:16)
    at HTMLUnknownElement.callCallback (react-dom.development.js:4164:14)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:4213:16)
    at invokeGuardedCallback (react-dom.development.js:4277:31)
    at beginWork$1 (react-dom.development.js:27446:7)
    at performUnitOfWork (react-dom.development.js:26552:12)
    at workLoopSync (react-dom.development.js:26461:5)
    at renderRootSync (react-dom.development.js:26429:7)
    at recoverFromConcurrentError (react-dom.development.js:25845:20)
    at performConcurrentWorkOnRoot (react-dom.development.js:25745:22)
    at workLoop (scheduler.development.js:266:34)
    at flushWork (scheduler.development.js:239:14)
    at MessagePort.performWorkUntilDeadline (scheduler.development.js:533:21)
```
```
The above error occurred in the <DeskToolBoundary> component:

    at DeskToolBoundary (webpack-internal:///../../../node_modules/.pnpm/sanity@3.2.5_z765n46jyysyfgk6yot2s5acla/node_modules/sanity/lib/_chunks/index-684ea917.js:4919:11)
    at Suspense
    at RouteScope (webpack-internal:///../../../node_modules/.pnpm/sanity@3.2.5_uzkadyugscbibgo6xwbyewzpjq/node_modules/sanity/lib/router.esm.js:184:5)
    at div
    at O (webpack-internal:///../../../node_modules/.pnpm/styled-components@5.3.6_7i5myeigehqah43i5u7wbekgba/node_modules/styled-components/dist/styled-components.browser.esm.js:31:19750)
    at Box2 (webpack-internal:///../../../node_modules/.pnpm/@sanity+ui@1.1.0_23mhwjhnzfjwvdn7ol54k26zom/node_modules/@sanity/ui/dist/index.esm.js:4448:9)
    at O (webpack-internal:///../../../node_modules/.pnpm/styled-components@5.3.6_7i5myeigehqah43i5u7wbekgba/node_modules/styled-components/dist/styled-components.browser.esm.js:31:19750)
    at Fe (webpack-internal:///../../../node_modules/.pnpm/styled-components@5.3.6_7i5myeigehqah43i5u7wbekgba/node_modules/styled-components/dist/styled-components.browser.esm.js:31:17299)
    at ThemeProvider (webpack-internal:///../../../node_modules/.pnpm/@sanity+ui@1.1.0_23mhwjhnzfjwvdn7ol54k26zom/node_modules/@sanity/ui/dist/index.esm.js:3203:72)
    at ThemeColorProvider (webpack-internal:///../../../node_modules/.pnpm/@sanity+ui@1.1.0_23mhwjhnzfjwvdn7ol54k26zom/node_modules/@sanity/ui/dist/index.esm.js:3262:5)
    at Card2 (webpack-internal:///../../../node_modules/.pnpm/@sanity+ui@1.1.0_23mhwjhnzfjwvdn7ol54k26zom/node_modules/@sanity/ui/dist/index.esm.js:4846:27)
    at ErrorBoundary (webpack-internal:///../../../node_modules/.pnpm/@sanity+ui@1.1.0_23mhwjhnzfjwvdn7ol54k26zom/node_modules/@sanity/ui/dist/index.esm.js:5369:5)
    at StudioErrorBoundary (webpack-internal:///../../../node_modules/.pnpm/sanity@3.2.5_uzkadyugscbibgo6xwbyewzpjq/node_modules/sanity/lib/index.esm.js:730:15776)
    at div
    at O (webpack-internal:///../../../node_modules/.pnpm/styled-components@5.3.6_7i5myeigehqah43i5u7wbekgba/node_modules/styled-components/dist/styled-components.browser.esm.js:31:19750)
    at Box2 (webpack-internal:///../../../node_modules/.pnpm/@sanity+ui@1.1.0_23mhwjhnzfjwvdn7ol54k26zom/node_modules/@sanity/ui/dist/index.esm.js:4448:9)
    at O (webpack-internal:///../../../node_modules/.pnpm/styled-components@5.3.6_7i5myeigehqah43i5u7wbekgba/node_modules/styled-components/dist/styled-components.browser.esm.js:31:19750)
    at Flex2 (webpack-internal:///../../../node_modules/.pnpm/@sanity+ui@1.1.0_23mhwjhnzfjwvdn7ol54k26zom/node_modules/@sanity/ui/dist/index.esm.js:4602:5)
    at StudioLayout$1 (webpack-internal:///../../../node_modules/.pnpm/sanity@3.2.5_uzkadyugscbibgo6xwbyewzpjq/node_modules/sanity/lib/index.esm.js:730:19025)
    at ResourceCacheProvider (webpack-internal:///../../../node_modules/.pnpm/sanity@3.2.5_uzkadyugscbibgo6xwbyewzpjq/node_modules/sanity/lib/index.esm.js:563:34386)
    at RouterProvider (webpack-internal:///../../../node_modules/.pnpm/sanity@3.2.5_uzkadyugscbibgo6xwbyewzpjq/node_modules/sanity/lib/router.esm.js:213:5)
    at SourceProvider (webpack-internal:///../../../node_modules/.pnpm/sanity@3.2.5_uzkadyugscbibgo6xwbyewzpjq/node_modules/sanity/lib/index.esm.js:706:18395)
    at WorkspaceProvider (webpack-internal:///../../../node_modules/.pnpm/sanity@3.2.5_uzkadyugscbibgo6xwbyewzpjq/node_modules/sanity/lib/index.esm.js:706:17928)
    at WorkspaceLoader (webpack-internal:///../../../node_modules/.pnpm/sanity@3.2.5_uzkadyugscbibgo6xwbyewzpjq/node_modules/sanity/lib/index.esm.js:759:1527)
    at ErrorBoundary (webpack-internal:///../../../node_modules/.pnpm/@sanity+ui@1.1.0_23mhwjhnzfjwvdn7ol54k26zom/node_modules/@sanity/ui/dist/index.esm.js:5369:5)
    at WorkspaceLoaderBoundary (webpack-internal:///../../../node_modules/.pnpm/sanity@3.2.5_uzkadyugscbibgo6xwbyewzpjq/node_modules/sanity/lib/index.esm.js:759:3902)
    at AuthBoundary (webpack-internal:///../../../node_modules/.pnpm/sanity@3.2.5_uzkadyugscbibgo6xwbyewzpjq/node_modules/sanity/lib/index.esm.js:755:372)
    at UserColorManagerProvider (webpack-internal:///../../../node_modules/.pnpm/sanity@3.2.5_uzkadyugscbibgo6xwbyewzpjq/node_modules/sanity/lib/index.esm.js:633:13802)
    at LayerProvider (webpack-internal:///../../../node_modules/.pnpm/@sanity+ui@1.1.0_23mhwjhnzfjwvdn7ol54k26zom/node_modules/@sanity/ui/dist/index.esm.js:5413:5)
    at Fe (webpack-internal:///../../../node_modules/.pnpm/styled-components@5.3.6_7i5myeigehqah43i5u7wbekgba/node_modules/styled-components/dist/styled-components.browser.esm.js:31:17299)
    at ThemeProvider (webpack-internal:///../../../node_modules/.pnpm/@sanity+ui@1.1.0_23mhwjhnzfjwvdn7ol54k26zom/node_modules/@sanity/ui/dist/index.esm.js:3203:72)
    at StudioThemeProvider (webpack-internal:///../../../node_modules/.pnpm/sanity@3.2.5_uzkadyugscbibgo6xwbyewzpjq/node_modules/sanity/lib/index.esm.js:755:1921)
    at ActiveWorkspaceMatcher (webpack-internal:///../../../node_modules/.pnpm/sanity@3.2.5_uzkadyugscbibgo6xwbyewzpjq/node_modules/sanity/lib/index.esm.js:729:1044)
    at WorkspacesProvider (webpack-internal:///../../../node_modules/.pnpm/sanity@3.2.5_uzkadyugscbibgo6xwbyewzpjq/node_modules/sanity/lib/index.esm.js:726:4469)
    at ErrorBoundary (webpack-internal:///../../../node_modules/.pnpm/@sanity+ui@1.1.0_23mhwjhnzfjwvdn7ol54k26zom/node_modules/@sanity/ui/dist/index.esm.js:5369:5)
    at StudioErrorBoundary (webpack-internal:///../../../node_modules/.pnpm/sanity@3.2.5_uzkadyugscbibgo6xwbyewzpjq/node_modules/sanity/lib/index.esm.js:730:15776)
    at ToastProvider (webpack-internal:///../../../node_modules/.pnpm/@sanity+ui@1.1.0_23mhwjhnzfjwvdn7ol54k26zom/node_modules/@sanity/ui/dist/index.esm.js:8693:5)
    at Fe (webpack-internal:///../../../node_modules/.pnpm/styled-components@5.3.6_7i5myeigehqah43i5u7wbekgba/node_modules/styled-components/dist/styled-components.browser.esm.js:31:17299)
    at ThemeProvider (webpack-internal:///../../../node_modules/.pnpm/@sanity+ui@1.1.0_23mhwjhnzfjwvdn7ol54k26zom/node_modules/@sanity/ui/dist/index.esm.js:3203:72)
    at ColorSchemeProvider (webpack-internal:///../../../node_modules/.pnpm/sanity@3.2.5_uzkadyugscbibgo6xwbyewzpjq/node_modules/sanity/lib/index.esm.js:726:2205)
    at StudioProvider (webpack-internal:///../../../node_modules/.pnpm/sanity@3.2.5_uzkadyugscbibgo6xwbyewzpjq/node_modules/sanity/lib/index.esm.js:759:5036)
    at div
    at O (webpack-internal:///../../../node_modules/.pnpm/styled-components@5.3.6_7i5myeigehqah43i5u7wbekgba/node_modules/styled-components/dist/styled-components.browser.esm.js:31:19750)
    at NextStudioLayoutComponent (webpack-internal:///../../../node_modules/.pnpm/next-sanity@4.1.1_s2dx7ip72t6n2pc3wrx5coznta/node_modules/next-sanity/dist/studio/index.js:47:5)
    at NextStudioClientOnly (webpack-internal:///../../../node_modules/.pnpm/next-sanity@4.1.1_s2dx7ip72t6n2pc3wrx5coznta/node_modules/next-sanity/dist/studio/index.js:25:5)
    at NextStudioComponent (webpack-internal:///../../../node_modules/.pnpm/next-sanity@4.1.1_s2dx7ip72t6n2pc3wrx5coznta/node_modules/next-sanity/dist/studio/index.js:62:5)
    at StudioPage
    at SWRConfig (webpack-internal:///../../../node_modules/.pnpm/swr@2.0.1_react@18.2.0/node_modules/swr/_internal/dist/index.mjs:540:13)
    at SessionProvider (webpack-internal:///../../../node_modules/.pnpm/next-auth@4.18.10_s6zlkfvllybxhmcq5pkr2zsuza/node_modules/next-auth/react/index.js:454:24)
    at App (webpack-internal:///./pages/_app.tsx:20:11)
    at PathnameContextProviderAdapter (webpack-internal:///../../../node_modules/.pnpm/next@13.1.5_pjwopsidmaokadturxaafygjp4/node_modules/next/dist/shared/lib/router/adapters.js:62:11)
    at ErrorBoundary (webpack-internal:///../../../node_modules/.pnpm/next@13.1.5_pjwopsidmaokadturxaafygjp4/node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:301:63)
    at ReactDevOverlay (webpack-internal:///../../../node_modules/.pnpm/next@13.1.5_pjwopsidmaokadturxaafygjp4/node_modules/next/dist/compiled/@next/react-dev-overlay/dist/client.js:850:919)
    at Container (webpack-internal:///../../../node_modules/.pnpm/next@13.1.5_pjwopsidmaokadturxaafygjp4/node_modules/next/dist/client/index.js:61:1)
    at AppContainer (webpack-internal:///../../../node_modules/.pnpm/next@13.1.5_pjwopsidmaokadturxaafygjp4/node_modules/next/dist/client/index.js:171:11)
    at Root (webpack-internal:///../../../node_modules/.pnpm/next@13.1.5_pjwopsidmaokadturxaafygjp4/node_modules/next/dist/client/index.js:346:11)

React will try to recreate this component tree from scratch using the error boundary you provided, ErrorBoundary.
```

**Comment by stipsan** [comment]
Hi, it looks like you're using `pnpm` but haven't setup [`auto-install-peers`](https://stackoverflow.com/a/74835069). Will update the docs 🤔
