### ISSUE TITLE
Live Preview with Next.js App Router and Sanity Studio

### ISSUE THREAD

**Issue by fpuglap** [sanity-io/next-sanity#588]
I'm trying this guide https://www.sanity.io/guides/nextjs-app-router-live-preview.

I was able to addres everything (it has errors but was able to fix them) but the Preview feature (the most important part of the guide).

Here is the reference https://www.sanity.io/guides/nextjs-app-router-live-preview#86c85dfb0cb7. 

I'm not sure why I'm getting the following error when go to http://localhost:3000/api/preview:
```
TypeError: cookies is not iterable
    at get [headers map sorted] (node:internal/deps/undici/undici:1844:34)
    at node:internal/deps/undici/undici:1865:43
    at Headers Iterator.next (node:internal/deps/undici/undici:1108:26)
    at toNodeOutgoingHttpHeaders (/Users/me/Dev/nextjs-app/node_modules/next/dist/server/web/utils.js:106:31)
    at invokeRender (/Users/me/Dev/nextjs-app/node_modules/next/dist/server/lib/router-server.js:275:122)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async handleRequest (/Users/me/Dev/nextjs-app/node_modules/next/dist/server/lib/router-server.js:447:24)
    at async requestHandler (/Users/me/Dev/nextjs-app/node_modules/next/dist/server/lib/router-server.js:464:13)
    at async Server.<anonymous> (/Users/me/Dev/nextjs-app/node_modules/next/dist/server/lib/start-server.js:117:13)
```

Any clues as to what may be going wrong?

Thanks!

**Comment by stipsan** [comment]
Hi @fpuglap :)

If you can share with us a reproduction case we'll be able to dig in and find the root of the problem. 
There's also a starter template on App Router that we often end-to-end test features such as live previews: https://github.com/sanity-io/sanity-template-nextjs-app-router-personal-website
If there's problems in our guide, as it has been rewritten during both the life cycle of App Router as well as our own preview-kit tooling, the template can be a fallback reference for you.
